#pragma once

#define BOOMERANG_ID 29000

#define BOOMERANG_SPRITES_PATH L"Content/Sprites/boomerang.txt"

#define BOOMERANG_ID_SPRITE_BOOMERANG_FRAME_0 29001
#define BOOMERANG_ID_SPRITE_BOOMERANG_FRAME_1 29002
#define BOOMERANG_ID_SPRITE_BOOMERANG_FRAME_2 29003
#define BOOMERANG_ID_SPRITE_BOOMERANG_FRAME_3 29004

#define BOOMERANG_ID_ANIMATION_BOOMERANG 29005
