#pragma once

#define FIRE_PIRANHA_ID 60000

#define FIRE_PIRANHA_SPRITES_PATH L"Content/Sprites/fire_piranha.txt"

#define FIRE_PIRANHA_ID_SPRITE_LOOK_DOWN_OPEN 60001
#define FIRE_PIRANHA_ID_SPRITE_LOOK_DOWN_CLOSE 60002
#define FIRE_PIRANHA_ID_SPRITE_LOOK_UP_OPEN 60003
#define FIRE_PIRANHA_ID_SPRITE_LOOK_UP_CLOSE 60004

