#pragma once

#define FIREWORK_ID 25000

#define FIREWORK_SPRITES_PATH L"Content/Sprites/firework.txt"

#define FIREWORK_ID_SPRITE_NORMAL_FRAME_0 25001
#define FIREWORK_ID_SPRITE_NORMAL_FRAME_1 25002
#define FIREWORK_ID_SPRITE_NORMAL_FRAME_2 25003
#define FIREWORK_ID_SPRITE_NORMAL_FRAME_3 25004

#define FIREWORK_ID_ANIMATION_NORMAL 25005
