#pragma once

#define FIREBALL_ID 80000

#define FIREBALL_SPRITES_PATH L"Content/Sprites/fireball.txt"

#define FIREBALL_ID_SPRITE_FIREBALL_FRAME_0 80001
#define FIREBALL_ID_SPRITE_FIREBALL_FRAME_1 80002
#define FIREBALL_ID_SPRITE_FIREBALL_FRAME_2 80003
#define FIREBALL_ID_SPRITE_FIREBALL_FRAME_3 80004

#define FIREBALL_ID_ANIMATION_FIREBALL 80005
