#pragma once

#define GREEN_PIRANHA_ID 19000

#define GREEN_PIRANHA_SPRITES_PATH L"Content/Sprites/green_piranha.txt"

#define GREEN_PIRANHA_ID_SPRITE_NORMAL_FRAME_0 19001
#define GREEN_PIRANHA_ID_SPRITE_NORMAL_FRAME_1 19002

#define GREEN_PIRANHA_ID_ANIMATION_NORMAL 19003
