#pragma once

#define HAMMER_BRO_ID 26000

#define HAMMER_BRO_SPRITES_PATH L"Content/Sprites/hammer_bro.txt"

#define HAMMER_BRO_ID_SPRITE_WALK_FRAME_0 26001
#define HAMMER_BRO_ID_SPRITE_WALK_FRAME_1 26002
#define HAMMER_BRO_ID_SPRITE_WALKTHROW_FRAME_0 26003
#define HAMMER_BRO_ID_SPRITE_WALKTHROW_FRAME_1 26004

#define HAMMER_BRO_ID_ANIMATION_WALK 26005
#define HAMMER_BRO_ID_ANIMATION_WALKTHROW 26006
