#pragma once

#define MARIO_BIG_ID 0

#define MARIO_BIG_SPRITES_PATH L"Content/Sprites/mariobig.txt"

#define MARIO_BIG_ID_SPRITE_IDLE_FRAME_0 1
#define MARIO_BIG_ID_SPRITE_WALK_FRAME_0 2
#define MARIO_BIG_ID_SPRITE_WALK_FRAME_1 3
#define MARIO_BIG_ID_SPRITE_JUMP_FRAME_0 4
#define MARIO_BIG_ID_SPRITE_RUNFLY_FRAME_0 5
#define MARIO_BIG_ID_SPRITE_RUNFLY_FRAME_1 6
#define MARIO_BIG_ID_SPRITE_FLY_FRAME_0 7
#define MARIO_BIG_ID_SPRITE_SKIDDING_FRAME_0 8
#define MARIO_BIG_ID_SPRITE_HOLD_IDLE_FRAME_0 9
#define MARIO_BIG_ID_SPRITE_HOLD_WALK_FRAME_0 10
#define MARIO_BIG_ID_SPRITE_HOLD_WALK_FRAME_1 11

#define MARIO_BIG_ID_ANIMATION_IDLE 12
#define MARIO_BIG_ID_ANIMATION_WALK 13
#define MARIO_BIG_ID_ANIMATION_JUMP 14
#define MARIO_BIG_ID_ANIMATION_RUNFLY 15
#define MARIO_BIG_ID_ANIMATION_FLY 16
#define MARIO_BIG_ID_ANIMATION_SKIDDING 17
#define MARIO_BIG_ID_ANIMATION_HOLD_IDLE 18
#define MARIO_BIG_ID_ANIMATION_HOLD_WALK 19
