#pragma once

#define QUESTION_BLOCK_ID 20000

#define QUESTION_BLOCK_SPRITES_PATH L"Content/Sprites/questionBlock.txt"

#define QUESTION_BLOCK_ID_SPRITE_IDLE_FRAME_0 20001
#define QUESTION_BLOCK_ID_SPRITE_IDLE_FRAME_1 20002
#define QUESTION_BLOCK_ID_SPRITE_IDLE_FRAME_2 20003
#define QUESTION_BLOCK_ID_SPRITE_IDLE_FRAME_3 20004
#define QUESTION_BLOCK_ID_SPRITE_EMPTY_FRAME_0 20005

#define QUESTION_BLOCK_ID_ANIMATION_IDLE 20006
#define QUESTION_BLOCK_ID_ANIMATION_EMPTY 20007
