#pragma once

#define RED_GOOMBA_ID 13000

#define RED_GOOMBA_SPRITES_PATH L"Content/Sprites/red_goomba.txt"

#define RED_GOOMBA_ID_SPRITE_WALK_FRAME_0 13001
#define RED_GOOMBA_ID_SPRITE_WALK_FRAME_1 13002
#define RED_GOOMBA_ID_SPRITE_DEAD_FRAME_0 13003

#define RED_GOOMBA_ID_ANIMATION_WALK 13004
#define RED_GOOMBA_ID_ANIMATION_DEAD 13005
