#pragma once

#define RED_GOOMBA_ID 50000

#define RED_GOOMBA_SPRITES_PATH L"Content/Sprites/red_goomba.txt"

#define RED_GOOMBA_ID_SPRITE_WALK_FRAME_0 50001
#define RED_GOOMBA_ID_SPRITE_WALK_FRAME_1 50002
#define RED_GOOMBA_ID_SPRITE_DEAD_FRAME_0 50003

#define RED_GOOMBA_ID_ANIMATION_WALK 50004
#define RED_GOOMBA_ID_ANIMATION_DEAD 50005
