#pragma once

// Maps
#define TEST_TILE_TMX "Content/Maps/test.tmx"
// Textures
#define TEXTURE_PATH_BTSPRITES L"Content/btSprites.png"
#define TEXTURE_ID_BTSPRITES 100

// Sprites
#define PLAYER_SPRITES 200
#define PLAYER_MOVEUP_FRAME1 PLAYER_SPRITES + 1
#define PLAYER_MOVEUP_FRAME2 PLAYER_SPRITES + 2
#define PLAYER_MOVERIGHT_FRAME1 PLAYER_SPRITES + 3
#define PLAYER_MOVERIGHT_FRAME2 PLAYER_SPRITES + 4
#define PLAYER_MOVELEFT_FRAME1 PLAYER_SPRITES + 5
#define PLAYER_MOVELEFT_FRAME2 PLAYER_SPRITES + 6
#define PLAYER_MOVEDOWN_FRAME1 PLAYER_SPRITES + 7
#define PLAYER_MOVEDOWN_FRAME2 PLAYER_SPRITES + 8
#define PLAYER_ANIMATION 300
#define PLAYER_MOVEUP_ANIMATION PLAYER_ANIMATION + 1
#define PLAYER_MOVERIGHT_ANIMATION PLAYER_ANIMATION + 2
#define PLAYER_MOVELEFT_ANIMATION PLAYER_ANIMATION + 3
#define PLAYER_MOVEDOWN_ANIMATION PLAYER_ANIMATION + 4

#define TANK_BULLET_SPRITE_ID 401

#define ENEMY_SPRITES 500
#define ENEMY_MOVEUP_FRAME1 ENEMY_SPRITES + 1
#define ENEMY_MOVEUP_FRAME2 ENEMY_SPRITES + 2
#define ENEMY_MOVERIGHT_FRAME1 ENEMY_SPRITES + 3
#define ENEMY_MOVERIGHT_FRAME2 ENEMY_SPRITES + 4
#define ENEMY_MOVELEFT_FRAME1 ENEMY_SPRITES + 5
#define ENEMY_MOVELEFT_FRAME2 ENEMY_SPRITES + 6
#define ENEMY_MOVEDOWN_FRAME1 ENEMY_SPRITES + 7
#define ENEMY_MOVEDOWN_FRAME2 ENEMY_SPRITES + 8
#define ENEMY_ANIMATION 600
#define ENEMY_MOVEUP_ANIMATION ENEMY_ANIMATION + 1
#define ENEMY_MOVERIGHT_ANIMATION ENEMY_ANIMATION + 2
#define ENEMY_MOVELEFT_ANIMATION ENEMY_ANIMATION + 3
#define ENEMY_MOVEDOWN_ANIMATION ENEMY_ANIMATION + 4