#pragma once

// Textures
#define SCENES_LIST_PATH				L"Content/Scenes/scenes_list.txt"
#define TEXTURE_PATH_BBOX				L"Content/bbox.png"

#define MARIO_ID 10000
    #define MARIO_SPRITES_PATH L"Content/Sprites/mario.txt"

    #define MARIO_ID_SPRITE_IDLE 11111

    #define MARIO_ID_SPRITE_WALK 11121

    #define MARIO_ID_SPRITE_JUMP 11131

    #define MARIO_ID_SPRITE_RUNNING_FRAME_1 11141
    #define MARIO_ID_SPRITE_RUNNING_FRAME_2 11142

    #define MARIO_ID_SPRITE_RUNNING_FLY 11151

    #define MARIO_ID_SPRITE_RUNNING_SKIDDING 11161

    #define MARIO_ID_SPRITE_RUNNING_DIE 11171

    #define MARIO_ID_ANIMATION_IDLE 400
    #define MARIO_ID_ANIMATION_WALKING 500
    #define MARIO_ID_ANIMATION_RUNNING 600
    #define MARIO_ID_ANIMATION_JUMP 700
    #define MARIO_ID_ANIMATION_SKIDDING 800
    #define MARIO_ID_ANIMATION_DIE 999

#define QUESTION_BLOCK_ID 20000
    #define QUESTION_BLOCK_SPRITES_PATH L"Content/Sprites/questionBlock.txt"

    #define QUESTION_BLOCK_ID_SPRITE_NORMAL_FRAME1 20010
    #define QUESTION_BLOCK_ID_SPRITE_NORMAL_FRAME2 20011
    #define QUESTION_BLOCK_ID_SPRITE_NORMAL_FRAME3 20012
    #define QUESTION_BLOCK_ID_SPRITE_NORMAL_FRAME4 20013

    #define QUESTION_BLOCK_ID_SPRITE_EMPTY 20014

    #define QUESTION_BLOCK_ID_ANIMATION_NORMAL 21010
    #define QUESTION_BLOCK_ID_ANIMATION_EMPTY 21020

#define COIN_ID 30000
    #define COIN_SPRITES_PATH L"Content/Sprites/coin.txt"

    #define COIN_ID_SPRITE_NORMAL_FRAME1 30010
    #define COIN_ID_SPRITE_NORMAL_FRAME2 30011
    #define COIN_ID_SPRITE_NORMAL_FRAME3 30012
    #define COIN_ID_SPRITE_NORMAL_FRAME4 30013
    
    #define COIN_ID_ANIMATION_NORMAL 31010