#pragma once

#define KOOPA_ID 0

#define KOOPA_SPRITE_PATH L"Content\Sprites\fire_piranha - Copy.txt"

#define KOOPA_ID_SPRITE_LOOK_DOWN_OPEN 1
#define KOOPA_ID_SPRITE_LOOK_DOWN_CLOSE 2
#define KOOPA_ID_SPRITE_LOOK_UP_OPEN 3
#define KOOPA_ID_SPRITE_LOOK_UP_OPEN 4
#define KOOPA_ID_SPRITE_NEW ANI_FRAME_0 5

#define KOOPA_ID_ANIMATION_NEW_ANI 6
